[workspace]
members = [
  "config",
  "lib/core",
  "lib/io/*",
  "lib/localisation",
  "lib/sensors",
  "lib/debugger"
]
exclude = [
  "boards/stm32l476rg",
  "boards/stm32h743zi",
  "boards/stm32f767zi",
  "boards/stm32l432kc",
]
resolver = "2"
