pods:
  poddington:
    label: 'Poddington'
    mode: 'LEVITATION_ONLY'
    measurements:
      accelerometer_1:
        label: 'Accelerometer 1'
        type: 'acceleration'
        unit: 'm/s²'
        format: 'float'
        limits:
          critical:
            low: -150
            high: 150
      accelerometer_2:
        label: 'Accelerometer 2'
        type: 'acceleration'
        unit: 'm/s²'
        format: 'float'
        limits:
          critical:
            low: -150
            high: 150
      accelerometer_3:
        label: 'Accelerometer 3'
        type: 'acceleration'
        unit: 'm/s²'
        format: 'float'
        limits:
          critical:
            low: -150
            high: 150
      accelerometer_4:
        label: 'Accelerometer 4'
        type: 'acceleration'
        unit: 'm/s²'
        format: 'float'
        limits:
          critical:
            low: -150
            high: 150
      accelerometer_avg:
        label: 'Accelerometer Average'
        type: 'acceleration'
        unit: 'm/s²'
        format: 'float'
        limits:
          critical:
            low: -150
            high: 150
      displacement:
        label: 'Displacement'
        type: 'displacement'
        unit: 'm'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      velocity:
        label: 'Velocity'
        type: 'velocity'
        unit: 'm/s'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 50
      acceleration:
        label: 'Acceleration'
        type: 'acceleration'
        unit: 'm/s²'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 5
      pressure_back_pull:
        label: 'Pressure – Back Pull'
        type: 'pressure'
        unit: 'bar'
        format: 'float'
        limits:
          critical:
            low: -0.2
            high: 5.5
          warning:
            low: -0.19
            high: 5.2
      pressure_front_pull:
        label: 'Pressure – Front Pull'
        type: 'pressure'
        unit: 'bar'
        format: 'float'
        limits:
          critical:
            low: -0.2
            high: 5.5
          warning:
            low: -0.19
            high: 5.2
      pressure_front_push:
        label: 'Pressure – Front Push'
        type: 'pressure'
        unit: 'bar'
        format: 'float'
        limits:
          critical:
            low: -0.2
            high: 5.5
          warning:
            low: -0.19
            high: 5.2
      pressure_back_push:
        label: 'Pressure – Back Push'
        type: 'pressure'
        unit: 'bar'
        format: 'float'
        limits:
          critical:
            low: -0.2
            high: 5.5
          warning:
            low: -0.19
            high: 5.2
      pressure_brakes_reservoir:
        label: 'Pressure – Brakes Reservoir'
        type: 'pressure'
        unit: 'bar'
        format: 'float'
        limits:
          critical:
            low: 3
            high: 7.4
          warning:
            low: 3.5
            high: 6.9
      pressure_active_suspension_reservoir:
        label: 'Pressure – Active Suspension Reservoir'
        type: 'pressure'
        unit: 'bar'
        format: 'float'
        limits:
          critical:
            low: 3
            high: 7.4
          warning:
            low: 3.5
            high: 6.9
      pressure_front_brake:
        label: 'Pressure – Front Brake'
        type: 'pressure'
        unit: 'bar'
        format: 'float'
        limits:
          critical:
            low: -0.2
            high: 4.2
          warning:
            low: -0.19
            high: 4
      pressure_back_brake:
        label: 'Pressure – Back Brake'
        type: 'pressure'
        unit: 'bar'
        format: 'float'
        limits:
          critical:
            low: -0.2
            high: 4.2
          warning:
            low: -0.19
            high: 4
      thermistor_1:
        label: 'Thermistor 1'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_2:
        label: 'Thermistor 2'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_3:
        label: 'Thermistor 3'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_4:
        label: 'Thermistor 4'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_5:
        label: 'Thermistor 5'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_6:
        label: 'Thermistor 6'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_7:
        label: 'Thermistor 7'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_8:
        label: 'Thermistor 8'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_9:
        label: 'Thermistor 9'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_10:
        label: 'Thermistor 10'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_11:
        label: 'Thermistor 11'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      thermistor_12:
        label: 'Thermistor 12'
        type: 'temperature'
        unit: '°C'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      hall_effect_1:
        label: 'Hall Effect 1'
        type: 'magnetism'
        unit: 'mT'
        format: 'float'
        limits:
          critical:
            low: -100
            high: 100
      hall_effect_2:
        label: 'Hall Effect 2'
        type: 'magnetism'
        unit: 'mT'
        format: 'float'
        limits:
          critical:
            low: -100
            high: 100
      keyence_1:
        label: 'Keyence 1'
        type: 'keyence'
        unit: 'number of stripes'
        format: 'integer'
        limits:
          critical:
            low: 0
            high: 16
          warning:
            low: 5
            high: 10
      keyence_2:
        label: 'Keyence 2'
        type: 'keyence'
        unit: 'number of stripes'
        format: 'integer'
        limits:
          critical:
            low: 0
            high: 16
          warning:
            low: 5
            high: 10
      power_line_resistance:
        label: 'Power Line Resistance'
        type: 'resistance'
        unit: 'kΩ'
        format: 'integer'
        limits:
          critical:
            low: 0
            high: 100
      levitation_height_1:
        label: 'Levitation Height 1'
        type: 'levitation'
        unit: 'mm'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      levitation_height_2:
        label: 'Levitation Height 2'
        type: 'levitation'
        unit: 'mm'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      levitation_height_3:
        label: 'Levitation Height 3'
        type: 'levitation'
        unit: 'mm'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      levitation_height_4:
        label: 'Levitation Height 4'
        type: 'levitation'
        unit: 'mm'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      levitation_height_lateral_1:
        label: 'Levitation Height Lateral 1'
        type: 'levitation'
        unit: 'mm'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
      levitation_height_lateral_2:
        label: 'Levitation Height Lateral 2'
        type: 'levitation'
        unit: 'mm'
        format: 'float'
        limits:
          critical:
            low: 0
            high: 100
    statuses:
      brake_clamp_status:
        label: 'Brake Clamp Status'
        type: 'binary-status'
        format: 'enum'
        values:
          - value: 1
            label: 'CLAMPED'
          - value: 0
            label: 'UNCLAMPED'
      pod_raised_status:
        label: 'Pod Raised Status'
        type: 'binary-status'
        format: 'enum'
        values:
          - value: 1
            label: 'RAISED'
          - value: 0
            label: 'LOWERED'
      battery_status:
        label: 'Battery Status'
        type: 'binary-status'
        format: 'enum'
        values:
          - value: 1
            label: 'HEALTHY'
          - value: 0
            label: 'UNHEALTHY'
      motor_controller_status:
        label: 'Motor Controller Status'
        type: 'binary-status'
        format: 'enum'
        values:
          - value: 1
            label: 'HEALTHY'
          - value: 0
            label: 'UNHEALTHY'
      high_power_status:
        label: 'High Power Status'
        type: 'binary-status'
        format: 'enum'
        values:
          - value: 1
            label: 'ACTIVE'
          - value: 0
            label: 'OFF'