# https://doc.rust-lang.org/cargo/guide/continuous-integration.html

name: Cargo Build & Test

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Cargo Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add thumbv7em-none-eabihf
      - run: cargo build --verbose
        working-directory: lib
      - run: cargo test --verbose
        working-directory: lib
      - run: cargo build --verbose
        working-directory: boards
      - run: cargo test --verbose
        working-directory: boards
      - run: cargo build --verbose
        working-directory: config
      - run: cargo test --verbose
        working-directory: config
