name: Linter

on: push

jobs:
  rust-clippy:
    name: Run clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning
          clippy_flags: --all-targets --all-features -- -Dwarnings

  rust-clippy-boards:
    name: Run clippy (boards)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - stm32l476rg
          - stm32f767zi
          - stm32l432kc
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add thumbv7em-none-eabihf
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-check'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: boards/${{ matrix.board }}
          level: warning
          clippy_flags: --all-features -- -Dwarnings

  rust-fmt:
    name: Run rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check

  rust-fmt-boards:
    name: Run rustfmt (boards)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - stm32l476rg
          - stm32f767zi
          - stm32l432kc
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --manifest-path boards/${{ matrix.board }}/Cargo.toml -- --check

  typos:
    name: Spell check with typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run typos
        uses: crate-ci/typos@master

  find-todos-fixme:
    name: Find todos and fixmes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run todo check
        run: |
          if grep -riE -n 'TODO|FIXME' * | grep -v -i 'TODOLater'; then
            exit 1
          else
            echo "All good"
          fi
