name: Linter

on: push

jobs:
  rust-clippy:
    name: Run clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  rust-clippy-boards:
    name: Run clippy (boards)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - stm32l476rg
          - stm32f767zi
          - stm32l432kc
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.board }}
      - name: Run clippy
        run: cd boards/${{ matrix.board }} && cargo clippy --all-features -- -D warnings

  rust-fmt:
    name: Run rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  rust-fmt-boards:
    name: Run rustfmt (boards)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - stm32l476rg
          - stm32f767zi
          - stm32l432kc
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cargo fmt --manifest-path boards/${{ matrix.board }}/Cargo.toml -- --check

  typos:
    name: Spell check with typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run typos
        uses: crate-ci/typos@master

  find-todos-fixme:
    name: Find todos and fixmes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run todo check
        run: |
          if grep -riE -n 'TODO|FIXME' * | grep -v -i 'TODOLater'; then
            exit 1
          else
            echo "All good"
          fi
