name: Telemetry

on: push

jobs:
  telemetry:
    name: Lint and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: telemetry
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build